ALTER TABLE alarm
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'Asia/Seoul';

ALTER TABLE salon_photos
ALTER COLUMN upload_date TYPE TIMESTAMP WITH TIME ZONE
USING upload_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE review
ALTER COLUMN reg_date TYPE TIMESTAMP WITH TIME ZONE
USING reg_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE review_photos
ALTER COLUMN upload_date TYPE TIMESTAMP WITH TIME ZONE
USING upload_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE point_usage
ALTER COLUMN use_date TYPE TIMESTAMP WITH TIME ZONE
USING use_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE archive
ALTER COLUMN reg_date TYPE TIMESTAMP WITH TIME ZONE
USING reg_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE archive_photos
ALTER COLUMN upload_date TYPE TIMESTAMP WITH TIME ZONE
USING upload_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE archive_comment
ALTER COLUMN reg_date TYPE TIMESTAMP WITH TIME ZONE
USING reg_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE community
ALTER COLUMN reg_date TYPE TIMESTAMP WITH TIME ZONE
USING reg_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE community_photos
ALTER COLUMN upload_date TYPE TIMESTAMP WITH TIME ZONE
USING upload_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE community_comment
ALTER COLUMN reg_date TYPE TIMESTAMP WITH TIME ZONE
USING reg_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE payment
ALTER COLUMN payment_date TYPE TIMESTAMP WITH TIME ZONE USING payment_date AT TIME ZONE 'Asia/Seoul',
ALTER COLUMN canceled_at TYPE TIMESTAMP WITH TIME ZONE USING canceled_at AT TIME ZONE 'Asia/Seoul';

ALTER TABLE chat_room
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'Asia/Seoul',
ALTER COLUMN last_message_time TYPE TIMESTAMP WITH TIME ZONE USING last_message_time AT TIME ZONE 'Asia/Seoul';

ALTER TABLE chat_message
ALTER COLUMN sent_at TYPE TIMESTAMP WITH TIME ZONE
USING sent_at AT TIME ZONE 'Asia/Seoul';

ALTER TABLE translation_cache
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'Asia/Seoul',
ALTER COLUMN last_used_at TYPE TIMESTAMP WITH TIME ZONE USING last_used_at AT TIME ZONE 'Asia/Seoul';

ALTER TABLE blacklist
ALTER COLUMN blocked_date TYPE TIMESTAMP WITH TIME ZONE
USING blocked_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE chat_photos
ALTER COLUMN upload_date TYPE TIMESTAMP WITH TIME ZONE
USING upload_date AT TIME ZONE 'Asia/Seoul';

ALTER TABLE coupon
ALTER COLUMN start_date TYPE TIMESTAMP WITH TIME ZONE USING start_date AT TIME ZONE 'Asia/Seoul',
ALTER COLUMN expiry_date TYPE TIMESTAMP WITH TIME ZONE USING expiry_date AT TIME ZONE 'Asia/Seoul',
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'Asia/Seoul';

ALTER TABLE review_reply
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'Asia/Seoul';

